# Generated by Django 5.2.3 on 2025-12-01 08:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('avatar_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Avatar', help_text='User-friendly name for the avatar', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the avatar', max_length=1000, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('archived', 'archived')], default='draft', help_text='Current status: draft/active/archived', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text="Whether this is the user's primary/active avatar")),
                ('canvas_json', models.JSONField(blank=True, help_text='Stores the avatar canvas state with all objects (512x512)', null=True)),
                ('rendered_image', models.ImageField(blank=True, help_text='Full size 512x512 rendered avatar image (PNG/WebP)', null=True, upload_to='avatar/images/rendered/')),
                ('thumbnail', models.ImageField(blank=True, help_text='128x128 thumbnail for avatar selection UI', null=True, upload_to='avatar/images/thumbnails/')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this avatar', on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
                'ordering': ['-is_primary', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ActiveAvatar',
            fields=[
            ],
            options={
                'verbose_name': 'Active Avatar',
                'verbose_name_plural': 'Active Avatars',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('avatar.avatar',),
        ),
        migrations.CreateModel(
            name='InactiveAvatar',
            fields=[
            ],
            options={
                'verbose_name': 'Inactive Avatar',
                'verbose_name_plural': 'Inactive Avatars',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('avatar.avatar',),
        ),
        migrations.AddIndex(
            model_name='avatar',
            index=models.Index(fields=['user', 'is_deleted'], name='avatar_avat_user_id_d9c232_idx'),
        ),
        migrations.AddIndex(
            model_name='avatar',
            index=models.Index(fields=['user', 'is_primary'], name='avatar_avat_user_id_3d43c3_idx'),
        ),
    ]
