# Generated by Django 5.2.3 on 2025-11-03 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=100)),
                ('brush_drip_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItemCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(help_text='Icon identifier for frontend', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Item Categories',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=4096)),
                ('status', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('archive', 'archive')])),
                ('picture', models.ImageField(default='static/images/default_600x400.png', upload_to='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_slots', models.IntegerField(default=12)),
                ('allow_free_positioning', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_award', to=settings.AUTH_USER_MODEL)),
                ('gallery_award_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gallery_award', to='gallery.awardtype')),
                ('gallery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_award', to='gallery.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.ImageField(upload_to='gallery/items/')),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', max_length=20)),
                ('is_achievement', models.BooleanField(default=False)),
                ('achievement_type', models.CharField(blank=True, help_text="e.g., 'first_post', 'top_artist', 'trophy_collector'", max_length=100, null=True)),
                ('achievement_date', models.DateTimeField(blank=True, null=True)),
                ('achievement_metadata', models.JSONField(blank=True, help_text='Additional achievement data', null=True)),
                ('related_post_id', models.CharField(blank=True, help_text='UUID of related post if applicable', max_length=255, null=True)),
                ('related_trophy_id', models.CharField(blank=True, help_text='ID of related trophy if applicable', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='gallery.galleryitemcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryLayout',
            fields=[
                ('layout_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_number', models.IntegerField(blank=True, help_text='Slot-based position (1-12), null for free positioning', null=True)),
                ('position_x', models.IntegerField(default=0, help_text='X coordinate in pixels or grid units')),
                ('position_y', models.IntegerField(default=0, help_text='Y coordinate in pixels or grid units')),
                ('width', models.IntegerField(default=200, help_text='Width in pixels')),
                ('height', models.IntegerField(default=200, help_text='Height in pixels')),
                ('z_index', models.IntegerField(default=0, help_text='Layer order for overlapping items')),
                ('rotation', models.FloatField(default=0, help_text='Rotation in degrees')),
                ('scale', models.FloatField(default=1.0, help_text='Scale factor')),
                ('opacity', models.FloatField(default=1.0, help_text='Opacity (0-1)')),
                ('border_color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('border_width', models.IntegerField(default=0, help_text='Border width in pixels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_items', to='gallery.gallery')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='gallery.galleryitem')),
            ],
            options={
                'ordering': ['z_index', 'slot_number'],
            },
        ),
        migrations.CreateModel(
            name='ItemFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.galleryitem')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reply_to_item', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('replies_to_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerycomment')),
                ('replies_to_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.itemfeedback')),
            ],
        ),
        migrations.CreateModel(
            name='ItemHeart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.galleryitem')),
            ],
        ),
    ]
