# Generated by Django 5.2.3 on 2025-07-08 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=100)),
                ('brush_drip_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.ImageField(default='gallery/items', upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_award', to=settings.AUTH_USER_MODEL)),
                ('gallery_award_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gallery_award', to='gallery.awardtype')),
                ('gallery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_award', to='gallery.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.galleryitem')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reply_to_item', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('replies_to_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerycomment')),
                ('replies_to_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.itemfeedback')),
            ],
        ),
        migrations.CreateModel(
            name='ItemHeart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.galleryitem')),
            ],
        ),
    ]
