# Generated by Django 5.2.3 on 2025-11-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfeedback',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemheart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemfeedback',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gallerycomment',
            name='replies_to_item',
        ),
        migrations.RemoveField(
            model_name='itemheart',
            name='author',
        ),
        migrations.RenameField(
            model_name='gallerycomment',
            old_name='replies_to_gallery',
            new_name='replies_to',
        ),
        migrations.RemoveField(
            model_name='gallerycomment',
            name='is_reply_to_item',
        ),
        migrations.DeleteModel(
            name='GalleryItem',
        ),
        migrations.DeleteModel(
            name='ItemFeedback',
        ),
        migrations.DeleteModel(
            name='ItemHeart',
        ),
    ]
