# Generated by Django 5.2.3 on 2025-10-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image_url',
            field=models.ImageField(default='static/images/default_600x400.png', upload_to=''),
        ),
    ]
