# Generated by Django 5.2.3 on 2025-10-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(default='static/images/default_600x400.png', upload_to=''),
        ),
    ]
