# Generated by Django 5.2.3 on 2025-11-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_itemfeedback_item_remove_itemheart_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(default='static/images/default_600x400.png', upload_to='gallery/'),
        ),
    ]
