# Generated by Django 5.2.3 on 2025-11-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_itemfeedback_item_remove_itemheart_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryComment',
        ),
    ]
