# Generated by Django 5.2.3 on 2025-11-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_squashed_0003_gallery_canvas_json_alter_gallery_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='canvas_height',
            field=models.IntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='gallery',
            name='canvas_width',
            field=models.IntegerField(default=1920),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(blank=True, default='static/images/default_600x400.png', upload_to='gallery/pictures/'),
        ),
    ]
