# Generated by Django 5.2.3 on 2025-11-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_delete_gallerycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='canvas_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
