# Generated by Django 5.2.3 on 2025-11-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_gallery_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(default='static/images/default_600x400.png', upload_to='gallery/'),
        ),
    ]
