# Generated by Django 5.2.3 on 2025-11-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallery_canvas_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('archived', 'archived')], default='draft'),
        ),
    ]
