# Generated by Django 5.2.3 on 2025-11-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallery_canvas_height_gallery_canvas_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGallery',
            fields=[
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.gallery',),
        ),
        migrations.CreateModel(
            name='InactiveGallery',
            fields=[
            ],
            options={
                'verbose_name': 'Inactive Gallery',
                'verbose_name_plural': 'Inactive Galleries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.gallery',),
        ),
    ]
