# Generated by Django 5.2.3 on 2025-12-02 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_activegallery_inactivegallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['creator', 'status', 'created_at'], name='gal_cr_stat_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['creator', 'is_deleted', 'created_at'], name='gal_cr_del_crt_idx'),
        ),
    ]
