# Generated by Django 5.2.3 on 2025-12-03 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_gallery_gal_cr_stat_crt_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryaward',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='awardtype',
            name='award',
            field=models.CharField(choices=[('bronze_stroke', 'bronze_stroke'), ('golden_bristle', 'golden_bristle'), ('diamond_canvas', 'diamond_canvas')], max_length=100),
        ),
        migrations.AddIndex(
            model_name='galleryaward',
            index=models.Index(fields=['gallery_id', 'author'], name='galleryaward_gal_author_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryaward',
            index=models.Index(fields=['author', 'awarded_at'], name='galleryaward_author_at_idx'),
        ),
    ]
