# Generated by Django 5.2.3 on 2025-12-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_galleryaward_is_deleted_alter_awardtype_award_and_more'),
        ('post', '0008_delete_collectivepost_delete_collectivepostcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryComment',
            fields=[
            ],
            options={
                'verbose_name': 'Gallery Comment',
                'verbose_name_plural': 'Gallery Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.comment',),
        ),
        migrations.CreateModel(
            name='GalleryCritique',
            fields=[
            ],
            options={
                'verbose_name': 'Gallery Critique',
                'verbose_name_plural': 'Gallery Critiques',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.critique',),
        ),
    ]
