# Generated by Django 5.2.3 on 2025-12-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_gallerycomment_gallerycritique'),
        ('post', '0008_delete_collectivepost_delete_collectivepostcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactiveGalleryComment',
            fields=[
            ],
            options={
                'verbose_name': 'Inactive Gallery Comment',
                'verbose_name_plural': 'Inactive Gallery Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.comment',),
        ),
        migrations.CreateModel(
            name='InactiveGalleryCritique',
            fields=[
            ],
            options={
                'verbose_name': 'Inactive Gallery Critique',
                'verbose_name_plural': 'Inactive Gallery Critiques',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.critique',),
        ),
    ]
