# Generated by Django 5.2.3 on 2025-11-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='gallery',
        ),
    ]
