# Generated by Django 5.2.3 on 2025-07-08 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='collective',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000001', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='collective.collective'),
        ),
    ]
