# Generated by Django 5.2.3 on 2025-07-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelpost',
            name='chapter',
            field=models.PositiveIntegerField(),
        ),
    ]
