# Generated by Django 5.2.3 on 2025-09-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='collective',
        ),
    ]
