# Generated by Django 5.2.3 on 2025-07-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_videopost_post_id_post_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('default', 'default'), ('novel', 'novel'), ('photo', 'photo'), ('video', 'video')], max_length=100),
        ),
    ]
