# Generated by Django 5.2.3 on 2025-12-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_squashed_0003_comment_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('default', 'default'), ('novel', 'novel'), ('image', 'image'), ('video', 'video')], help_text='Type of post: "default" for standard posts, "novel" for novel chapters (requires NovelPost), "image" for image galleries, "video" for video content.', max_length=100),
        ),
    ]
