# Generated by Django 5.2.3 on 2025-09-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_collective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critique',
            name='replying_to',
        ),
    ]
