# Generated by Django 5.2.3 on 2025-07-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_comment_id_remove_critique_id_remove_event_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttrophy',
            old_name='praised_at',
            new_name='awarded_at',
        ),
    ]
