# Generated by Django 5.2.3 on 2025-12-02 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0003_collectivemember_cmember_member_coll_idx_and_more'),
        ('gallery', '0006_gallery_gal_cr_stat_crt_idx_and_more'),
        ('post', '0004_alter_post_post_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post_id', 'is_deleted', 'created_at'], name='comment_post_del_created_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'created_at'], name='comment_author_created_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['gallery', 'is_deleted', 'created_at'], name='cmt_gal_del_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['critique_id', 'is_deleted', 'created_at'], name='comment_crit_del_created_idx'),
        ),
        migrations.AddIndex(
            model_name='critique',
            index=models.Index(fields=['post_id', 'is_deleted', 'created_at'], name='critique_post_del_created_idx'),
        ),
        migrations.AddIndex(
            model_name='critique',
            index=models.Index(fields=['author', 'created_at'], name='critique_author_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author_id', 'created_at'], name='post_author_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['channel_id', 'created_at'], name='post_channel_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', 'created_at'], name='post_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_deleted', 'created_at'], name='post_deleted_created_idx'),
        ),
        migrations.AddIndex(
            model_name='postheart',
            index=models.Index(fields=['author', 'post_id'], name='postheart_author_post_idx'),
        ),
        migrations.AddIndex(
            model_name='postheart',
            index=models.Index(fields=['post_id', 'author'], name='postheart_post_author_idx'),
        ),
        migrations.AddIndex(
            model_name='postheart',
            index=models.Index(fields=['author', 'hearted_at'], name='postheart_author_at_idx'),
        ),
        migrations.AddIndex(
            model_name='postpraise',
            index=models.Index(fields=['author', 'post_id'], name='postpraise_author_post_idx'),
        ),
        migrations.AddIndex(
            model_name='postpraise',
            index=models.Index(fields=['post_id', 'author'], name='postpraise_post_author_idx'),
        ),
        migrations.AddIndex(
            model_name='postpraise',
            index=models.Index(fields=['author', 'praised_at'], name='postpraise_author_at_idx'),
        ),
        migrations.AddIndex(
            model_name='posttrophy',
            index=models.Index(fields=['author', 'post_id'], name='posttrophy_author_post_idx'),
        ),
        migrations.AddIndex(
            model_name='posttrophy',
            index=models.Index(fields=['post_id', 'author'], name='posttrophy_post_author_idx'),
        ),
        migrations.AddIndex(
            model_name='posttrophy',
            index=models.Index(fields=['author', 'awarded_at'], name='posttrophy_author_at_idx'),
        ),
    ]
