# Generated by Django 5.2.3 on 2025-12-03 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_galleryaward_is_deleted_alter_awardtype_award_and_more'),
        ('post', '0005_comment_comment_post_del_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='critique',
            name='gallery_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_critique', to='gallery.gallery'),
        ),
        migrations.AddIndex(
            model_name='critique',
            index=models.Index(fields=['gallery_id', 'is_deleted', 'created_at'], name='critique_gal_del_created_idx'),
        ),
    ]
