# Generated by Django 5.2.3 on 2025-10-03 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_comment_is_deleted_critique_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='critique_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='critique_comment', to='post.critique'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reply', to='post.comment'),
        ),
        migrations.DeleteModel(
            name='CritiqueComment',
        ),
    ]
