# Generated by Django 5.2.3 on 2025-10-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_comment_critique_id_comment_replies_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_critique_reply',
            field=models.BooleanField(default=False),
        ),
    ]
