# Generated by Django 5.2.3 on 2025-12-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_critique_gallery_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectivePost',
            fields=[
            ],
            options={
                'verbose_name': 'Collective Post',
                'verbose_name_plural': 'Collective Posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='CollectivePostComment',
            fields=[
            ],
            options={
                'verbose_name': 'Collective Post Comment',
                'verbose_name_plural': 'Collective Post Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.comment',),
        ),
        migrations.CreateModel(
            name='CollectivePostCritique',
            fields=[
            ],
            options={
                'verbose_name': 'Collective Post Critique',
                'verbose_name_plural': 'Collective Post Critiques',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.critique',),
        ),
        migrations.CreateModel(
            name='GalleryComment',
            fields=[
            ],
            options={
                'verbose_name': 'Gallery Comment',
                'verbose_name_plural': 'Gallery Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.comment',),
        ),
        migrations.CreateModel(
            name='GalleryCritique',
            fields=[
            ],
            options={
                'verbose_name': 'Gallery Critique',
                'verbose_name_plural': 'Gallery Critiques',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.critique',),
        ),
    ]
