# Generated by Django 5.2.3 on 2025-10-06 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_comment_is_critique_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='critique_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='critique_reply', to='post.critique'),
        ),
    ]
