# Generated by Django 5.2.3 on 2025-12-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_collectivepost_collectivepostcomment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectivePost',
        ),
        migrations.DeleteModel(
            name='CollectivePostComment',
        ),
        migrations.DeleteModel(
            name='CollectivePostCritique',
        ),
        migrations.DeleteModel(
            name='GalleryComment',
        ),
        migrations.DeleteModel(
            name='GalleryCritique',
        ),
    ]
