# Generated by Django 5.2.3 on 2025-10-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactiveComment',
            fields=[
            ],
            options={
                'verbose_name': 'Inactive Comment',
                'verbose_name_plural': 'Inactive Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.comment',),
        ),
        migrations.CreateModel(
            name='InactiveCritique',
            fields=[
            ],
            options={
                'verbose_name': 'Inactive Critique',
                'verbose_name_plural': 'Inactive Critiques',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.critique',),
        ),
        migrations.CreateModel(
            name='InactivePost',
            fields=[
            ],
            options={
                'verbose_name': 'Inactive Post',
                'verbose_name_plural': 'Inactive Posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.post',),
        ),
    ]
