# Generated by Django 5.2.3 on 2025-11-11 08:21

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_inactivecomment_inactivecritique_inactivepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='posts/videos/'),
        ),
    ]
