# Generated by Django 5.2.3 on 2025-11-06 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_delete_gallerycomment'),
        ('post', '0010_inactivecomment_inactivecritique_inactivepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_comment', to='gallery.gallery'),
        ),
    ]
