# Generated by Django 5.2.3 on 2025-09-02 08:25

import collective.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collective',
            fields=[
                ('collective_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=4096)),
                ('status', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('archive', 'archive')], max_length=100)),
                ('rules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=collective.models.Collective.default_rules, size=None)),
                ('artist_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Select artist types (e.g. visual arts, literary arts, etc.)', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectiveMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collective_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collective_member', to='collective.collective')),
            ],
        ),
    ]
