# Generated by Django 5.2.3 on 2025-11-12 06:02

import collective.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collective',
            fields=[
                ('collective_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=4096)),
                ('rules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=collective.models.Collective.default_rules, size=None)),
                ('artist_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Select artist types (e.g. visual arts, literary arts, etc.)', size=None)),
                ('picture', models.ImageField(default='static/images/defaut_600x400.png', upload_to='collective/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('channel_type', models.CharField(choices=[('post_channel', 'Post Channel'), ('media_channel', 'Media Channel'), ('event_channel', 'Event Channel')], default='post_channel', max_length=50)),
                ('description', models.CharField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collective_channel', to='collective.collective')),
            ],
        ),
        migrations.CreateModel(
            name='CollectiveMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collective_role', models.CharField(choices=[('member', 'member'), ('admin', 'admin')], default='member', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collective_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collective_member', to='collective.collective')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collective_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from requester', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admin_requests', to=settings.AUTH_USER_MODEL)),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_requests', to='collective.collective')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('collective', 'requester', 'status')},
            },
        ),
    ]
