# Generated by Django 5.2.3 on 2025-11-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collective',
            name='picture',
            field=models.ImageField(default='static/images/default_600x400.png', upload_to='collective/'),
        ),
    ]
