# Generated by Django 5.2.3 on 2025-07-08 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='collective',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collective',
            name='status',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private'), ('archive', 'archive')], default='public', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collective',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
