# Generated by Django 5.2.3 on 2025-09-02 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='collective',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000001', on_delete=django.db.models.deletion.CASCADE, related_name='collective_channel', to='collective.collective'),
            preserve_default=False,
        ),
    ]
