# Generated by Django 5.2.3 on 2025-07-08 17:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0002_channel_created_at_channel_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collective',
            name='rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=['Be respectful and kind to others.', 'No spam or self-promotion.', 'Stay on topic and keep discussions relevant.', 'No hate speech or discriminatory language.', 'Respect privacy — no sharing personal information without consent.', 'Follow Facebook Community Guidelines.'], size=None),
        ),
    ]
