# Generated by Django 5.2.3 on 2025-12-02 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0002_alter_collective_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collectivemember',
            index=models.Index(fields=['member', 'collective_id'], name='cmember_member_coll_idx'),
        ),
        migrations.AddIndex(
            model_name='collectivemember',
            index=models.Index(fields=['collective_id', 'member'], name='cmember_coll_member_idx'),
        ),
    ]
