# Generated by Django 5.2.3 on 2025-09-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0003_channel_collective'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('post_channel', 'Post Channels'), ('media_channel', 'Media Channels'), ('event_channel', 'Event Channels')], default='post_channel', max_length=50),
        ),
    ]
