# Generated by Django 5.2.3 on 2025-07-08 17:46

import collective.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0003_collective_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collective',
            name='rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=collective.models.Collective.default_rules, size=None),
        ),
    ]
