# Generated by Django 5.2.3 on 2025-12-04 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0003_collectivemember_cmember_member_coll_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rules_accepted', models.BooleanField(default=False, help_text="Flag indicating user has accepted the collective's rules")),
                ('message', models.TextField(blank=True, help_text='Optional message from requester', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='collective.collective')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['collective', 'status'], name='join_req_coll_status_idx'), models.Index(fields=['requester', 'status'], name='join_req_req_status_idx')],
                'unique_together': {('collective', 'requester', 'status')},
            },
        ),
    ]
