# Generated by Django 5.2.3 on 2025-09-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0004_channel_channel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collective',
            name='status',
        ),
    ]
