# Generated by Django 5.2.3 on 2025-07-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0004_alter_collective_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='collective',
            name='description',
            field=models.CharField(max_length=4096),
        ),
    ]
