# Generated by Django 5.2.3 on 2025-12-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0004_joinrequest'),
        ('post', '0008_delete_collectivepost_delete_collectivepostcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectivePost',
            fields=[
            ],
            options={
                'verbose_name': 'Collective Post',
                'verbose_name_plural': 'Collective Posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='CollectivePostComment',
            fields=[
            ],
            options={
                'verbose_name': 'Collective Post Comment',
                'verbose_name_plural': 'Collective Post Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.comment',),
        ),
        migrations.CreateModel(
            name='CollectivePostCritique',
            fields=[
            ],
            options={
                'verbose_name': 'Collective Post Critique',
                'verbose_name_plural': 'Collective Post Critiques',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.critique',),
        ),
    ]
