# Generated by Django 5.2.3 on 2025-09-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0005_remove_collective_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectivemember',
            name='collective_role',
            field=models.CharField(choices=[('member', 'member'), ('admin', 'admin')], default='member', max_length=50),
        ),
    ]
