# Generated by Django 5.2.3 on 2025-12-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0005_collectivepost_collectivepostcomment_and_more'),
        ('post', '0008_delete_collectivepost_delete_collectivepostcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactiveCollectivePost',
            fields=[
            ],
            options={
                'verbose_name': 'Inactive Collective Post',
                'verbose_name_plural': 'Inactive Collective Posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='InactiveCollectivePostComment',
            fields=[
            ],
            options={
                'verbose_name': 'Inactive Collective Post Comment',
                'verbose_name_plural': 'Inactive Collective Post Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.comment',),
        ),
        migrations.CreateModel(
            name='InactiveCollectivePostCritique',
            fields=[
            ],
            options={
                'verbose_name': 'Inactive Collective Post Critique',
                'verbose_name_plural': 'Inactive Collective Post Critiques',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.critique',),
        ),
    ]
