# Generated by Django 5.2.3 on 2025-09-14 11:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0006_collectivemember_collective_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectivemember',
            unique_together={('member', 'collective_id')},
        ),
    ]
