# Generated by Django 5.2.3 on 2025-09-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0007_alter_collectivemember_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectivemember',
            unique_together=set(),
        ),
    ]
