# Generated by Django 5.2.3 on 2025-09-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0008_alter_collectivemember_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('post_channel', 'Post Channel'), ('media_channel', 'Media Channel'), ('event_channel', 'Event Channel')], default='post_channel', max_length=50),
        ),
    ]
