# Generated by Django 5.2.3 on 2025-10-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0009_alter_channel_channel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collective',
            name='picture',
            field=models.ImageField(default='static/images/defaut_600x400.png', upload_to=''),
        ),
    ]
