# Generated by Django 5.2.3 on 2025-10-30 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0011_adminrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectivemember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectivemember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
