# Generated by Django 5.2.3 on 2025-11-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0012_collectivemember_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collective',
            name='picture',
            field=models.ImageField(default='static/images/defaut_600x400.png', upload_to='collective/'),
        ),
    ]
