# Generated by Django 5.2.3 on 2025-11-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective', '0013_alter_collective_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collective',
            name='picture',
            field=models.ImageField(default='static/images/defaut_600x400__azzmrg.png', upload_to='collective/'),
        ),
    ]
