# Generated by Django 5.2.3 on 2025-07-08 12:23

from django.db import migrations
from decouple import config

def create_initial_data(apps, schema_editor):
    Collective = apps.get_model('collective', 'Collective')
    User = apps.get_model('account', 'User')

    default_collectives = [
        {
            'collective_id': '00000000-0000-0000-0000-000000000001',
            'title': 'public',
            'description': 'This post is a public post',
        }
    ]
    
    default_user = {
        'username': config('ADMIN_USER'),
        'password': config('ADMIN_PASS'),
        'email': config('ADMIN_EMAIL'),
    }
    
    for collective in default_collectives:
        Collective.objects.get_or_create(
            title=collective['title'],
            description=collective['description'],
        )
        
    if not User.objects.filter(is_superuser=True).exists():
        User.objects.create_superuser(
            username=default_user['username'],
            email=default_user['email'],
            password=default_user['password']
        )

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_data,
        )
    ]

# python manage.py makemigrations --empty account --name seed_initial_data
