export type CollectivePostContextType = {
    collectiveData,
    loading,
    selectedChannel,
    setSelectedChannel,
    fetchCollectiveData,
    handleCreateChannel,
    showCreateChannelModal,
    setShowCreateChannelModal,
    createChannelForm,
    setCreateChannelForm,
    creatingChannel,
    setCreatingChannel,
    editingChannel, setEditingChannel,
    updatingChannel, setUpdatingChannel,
    deletingChannel, setDeletingChannel,
    handleUpdateChannel,
    handleDeleteChannel,
}