# Generated by Django 5.2.3 on 2025-10-19 07:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('notification_object_type', models.CharField(choices=[('post_comment', 'Post Comment'), ('post_critique', 'Post Critique'), ('post_praise', 'Post Praise'), ('post_trophy', 'Post Trophy')], max_length=500)),
                ('notification_object_id', models.CharField(max_length=2000)),
                ('is_read', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('notified_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationNotifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
                ('notified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
