# Generated by Django 5.2.3 on 2025-12-02 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_object_type',
            field=models.CharField(choices=[('post_comment', 'Post Comment'), ('post_critique', 'Post Critique'), ('post_praise', 'Post Praise'), ('post_trophy', 'Post Trophy'), ('gallery_comment', 'Gallery Comment'), ('friend_request_accepted', 'Friend Request Accepted')], max_length=500),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notified_to', 'is_read', 'notified_at'], name='notification_user_read_at_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notified_to', 'notification_object_type'], name='notification_user_type_idx'),
        ),
    ]
