# Generated by Django 5.2.3 on 2025-12-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_notification_object_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_object_type',
            field=models.CharField(choices=[('post_comment', 'Post Comment'), ('post_critique', 'Post Critique'), ('post_praise', 'Post Praise'), ('post_trophy', 'Post Trophy'), ('gallery_comment', 'Gallery Comment'), ('gallery_award', 'Gallery Award'), ('friend_request_accepted', 'Friend Request Accepted')], max_length=500),
        ),
    ]
