# Generated by Django 5.2.3 on 2025-12-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_notification_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_object_type',
            field=models.CharField(choices=[('post_comment', 'Post Comment'), ('post_critique', 'Post Critique'), ('post_praise', 'Post Praise'), ('post_trophy', 'Post Trophy'), ('gallery_comment', 'Gallery Comment'), ('gallery_critique', 'Gallery Critique'), ('gallery_award', 'Gallery Award'), ('friend_request_accepted', 'Friend Request Accepted'), ('join_request_accepted', 'Join Request Accepted'), ('admin_request_accepted', 'Admin Request Accepted'), ('join_request_created', 'Join Request Created'), ('admin_request_created', 'Admin Request Created')], max_length=500),
        ),
    ]
