# Generated by Django 5.2.3 on 2025-12-05 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='The search query string', max_length=255)),
                ('search_type', models.CharField(choices=[('all', 'All'), ('users', 'Users'), ('posts', 'Posts'), ('collectives', 'Collectives'), ('galleries', 'Galleries')], default='all', help_text='Type of search performed', max_length=20)),
                ('result_count', models.IntegerField(default=0, help_text='Number of results found')),
                ('is_successful', models.BooleanField(default=False, help_text='Whether results were found')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Search History',
                'verbose_name_plural': 'User Search Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='search_hist_user_created_idx'), models.Index(fields=['query'], name='search_history_query_idx')],
            },
        ),
    ]
