# Generated by Django 5.2.3 on 2025-11-12 06:01

import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='N/A', max_length=100)),
                ('country', models.CharField(blank=True, default='N/A', max_length=100)),
                ('contact_no', models.CharField(blank=True, default='N/A', max_length=20)),
                ('birthday', models.DateField(blank=True, help_text="Enter user's date of birth", null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(default='static/images/default-pic-min.jpg', upload_to='profile/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='artist', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('artist_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Select artist types (e.g. visual arts, literary arts, etc.)', size=None)),
            ],
        ),
        migrations.CreateModel(
            name='InactiveUser',
            fields=[
            ],
            options={
                'verbose_name': 'Inactive User',
                'verbose_name_plural': 'Inactive Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='BrushDripWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFellow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('blocked', 'blocked')], default='pending')),
                ('fellowed_at', models.DateTimeField(auto_now_add=True)),
                ('fellow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_relationship_as_fellow', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_relationship', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrushDripTransaction',
            fields=[
                ('drip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('transaction_object_type', models.CharField(choices=[('praise', 'Praise'), ('trophy', 'Trophy'), ('critique', 'Critique'), ('admin_override', 'Admin Override')], max_length=500)),
                ('transaction_object_id', models.CharField(max_length=2000)),
                ('transacted_at', models.DateTimeField(auto_now_add=True)),
                ('transacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brushdrip_transacted_by', to=settings.AUTH_USER_MODEL)),
                ('transacted_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brushdrip_transacted_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['transacted_by'], name='core_brushd_transac_76da42_idx'), models.Index(fields=['transacted_to'], name='core_brushd_transac_d187a1_idx'), models.Index(fields=['transaction_object_type', 'transaction_object_id'], name='core_brushd_transac_02d494_idx')],
            },
        ),
    ]
