# Generated by Django 5.2.3 on 2025-10-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='static/images/default-pic-min.jpg', upload_to='profile/images/'),
        ),
    ]
