# Generated by Django 5.2.3 on 2025-10-09 09:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrushDripTransaction',
            fields=[
                ('drip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('transaction_object_type', models.CharField(choices=[('praise', 'Praise'), ('brush_gradient', 'Brush Gradient'), ('critique', 'Critique')], max_length=500)),
                ('transaction_object_id', models.CharField(max_length=2000)),
                ('transacted_at', models.DateTimeField(auto_now_add=True)),
                ('transacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brushdrip_transacted_by', to=settings.AUTH_USER_MODEL)),
                ('transacted_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brushdrip_transacted_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrushDripWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
