# Generated by Django 5.2.3 on 2025-11-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_artist_to_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this artist profile should be treated as deleted.'),
        ),
        migrations.AddField(
            model_name='brushdripwallet',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this wallet should be treated as deleted.'),
        ),
        migrations.AddField(
            model_name='userfellow',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this relationship should be treated as deleted.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as deleted. Unselect this instead of deleting accounts.'),
        ),
    ]
