# Generated by Django 5.2.3 on 2025-07-09 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFellow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('blocked', 'blocked')], default='pending')),
                ('fellowed_at', models.DateTimeField(auto_now_add=True)),
                ('fellow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_relationship_as_fellow', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_relationship', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
