# Generated by Django 5.2.3 on 2025-12-02 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_artist_is_deleted_brushdripwallet_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('preferred_post_types', models.JSONField(blank=True, default=list, help_text='List of preferred post types, e.g. ["image", "novel", "video"]')),
                ('preferred_artist_types', models.JSONField(blank=True, default=list, help_text='List of preferred artist types, e.g. ["visual_arts", "literary_arts"]')),
                ('muted_collectives', models.JSONField(blank=True, default=list, help_text='List of collective IDs to hide posts from (future feature)')),
                ('blocked_users', models.JSONField(blank=True, default=list, help_text='List of user IDs to hide posts from (future feature)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.AddIndex(
            model_name='userfellow',
            index=models.Index(fields=['user', 'fellow_user', 'status'], name='userfellow_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='userfellow',
            index=models.Index(fields=['user', 'status', 'is_deleted'], name='ufellow_user_stat_del_idx'),
        ),
        migrations.AddIndex(
            model_name='userfellow',
            index=models.Index(fields=['fellow_user', 'status', 'is_deleted'], name='ufellow_fellow_stat_del_idx'),
        ),
    ]
