# Generated by Django 5.2.3 on 2025-10-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_brushdriptransaction_brushdripwallet'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brushdriptransaction',
            index=models.Index(fields=['transacted_by'], name='core_brushd_transac_76da42_idx'),
        ),
        migrations.AddIndex(
            model_name='brushdriptransaction',
            index=models.Index(fields=['transacted_to'], name='core_brushd_transac_d187a1_idx'),
        ),
        migrations.AddIndex(
            model_name='brushdriptransaction',
            index=models.Index(fields=['transaction_object_type', 'transaction_object_id'], name='core_brushd_transac_02d494_idx'),
        ),
    ]
