# Generated by Django 5.2.3 on 2025-12-03 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_userpreference_userfellow_userfellow_lookup_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Reputation change amount (positive or negative)')),
                ('source_type', models.CharField(choices=[('praise', 'Praise'), ('trophy', 'Trophy'), ('critique', 'Critique'), ('gallery_award', 'Gallery Award')], help_text='Type of interaction that caused the reputation change', max_length=50)),
                ('source_id', models.CharField(help_text='ID of the source object (praise_id, trophy_id, critique_id, award_id)', max_length=2000)),
                ('source_object_type', models.CharField(blank=True, help_text='Type of object the source belongs to (post, gallery)', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the reputation change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reputation History',
                'verbose_name_plural': 'Reputation Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='reputation',
            field=models.IntegerField(default=0, help_text='User reputation score based on interactions'),
        ),
        migrations.AlterField(
            model_name='brushdriptransaction',
            name='transaction_object_type',
            field=models.CharField(choices=[('praise', 'Praise'), ('trophy', 'Trophy'), ('critique', 'Critique'), ('gallery_award', 'Gallery Award'), ('admin_override', 'Admin Override')], max_length=500),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['reputation', 'id'], name='user_reputation_id_idx'),
        ),
        migrations.AddField(
            model_name='reputationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reputationhistory',
            index=models.Index(fields=['user', 'created_at'], name='rep_history_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='reputationhistory',
            index=models.Index(fields=['source_type', 'source_id'], name='rep_history_source_idx'),
        ),
        migrations.AddIndex(
            model_name='reputationhistory',
            index=models.Index(fields=['created_at'], name='rep_history_created_idx'),
        ),
    ]
