# Generated by Django 5.2.3 on 2025-10-09 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_brushdriptransaction_core_brushd_transac_76da42_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brushdripwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
