# Generated by Django 5.2.3 on 2025-10-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_brushdripwallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brushdriptransaction',
            name='transaction_object_type',
            field=models.CharField(choices=[('praise', 'Praise'), ('trophy', 'Trophy'), ('brush_gradient', 'Brush Gradient'), ('critique', 'Critique')], max_length=500),
        ),
    ]
