# Generated by Django 5.2.3 on 2025-08-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_birthday_alter_user_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile/images/default-pic-min.jpg', upload_to=''),
        ),
    ]
