# Generated by Django 5.2.3 on 2025-12-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reputationhistory_alter_user_options_user_reputation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brushdriptransaction',
            name='transaction_object_type',
            field=models.CharField(choices=[('praise', 'Praise'), ('trophy', 'Trophy'), ('critique', 'Critique'), ('gallery_critique', 'Gallery Critique'), ('gallery_award', 'Gallery Award'), ('admin_override', 'Admin Override')], max_length=500),
        ),
    ]
