# Generated by Django 5.2.3 on 2025-10-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_brushdriptransaction_transaction_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brushdriptransaction',
            name='transaction_object_type',
            field=models.CharField(choices=[('praise', 'Praise'), ('trophy', 'Trophy'), ('critique', 'Critique')], max_length=500),
        ),
    ]
