# Generated by Django 5.2.3 on 2025-12-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_brushdriptransaction_transaction_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputationhistory',
            name='source_type',
            field=models.CharField(choices=[('praise', 'Praise'), ('trophy', 'Trophy'), ('critique', 'Critique'), ('gallery_critique', 'Gallery Critique'), ('gallery_award', 'Gallery Award')], help_text='Type of interaction that caused the reputation change', max_length=50),
        ),
    ]
