# Generated by Django 5.2.3 on 2025-10-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactiveUser',
            fields=[
            ],
            options={
                'verbose_name': 'Inactive User',
                'verbose_name_plural': 'Inactive Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
        ),
    ]
