# Generated by Django 5.2.3 on 2025-10-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inactiveuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brushdriptransaction',
            name='transaction_object_type',
            field=models.CharField(choices=[('praise', 'Praise'), ('trophy', 'Trophy'), ('critique', 'Critique'), ('admin_override', 'Admin Override')], max_length=500),
        ),
    ]
