# Generated by Django 5.2.3 on 2025-11-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='static/images/default-pic-min_bckmti.jpg', upload_to='profile/'),
        ),
    ]
