# Generated by Django 5.2.3 on 2025-11-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='static/images/default-pic-min.jpg', upload_to='profile/'),
        ),
    ]
